### ISSUE TITLE
Allow reverse engineering database views

### ISSUE THREAD

**Issue by timarthurlee** [ErikEJ/SqlCeToolbox#765] opened 2018-12-19 16:50 UTC
When attempting to reverse engineer a database view, only tables are available for selection. Please also include views,

**Comment by ErikEJ** [comment] 2018-12-19 17:04
I think you are in the wrong repo, possible duplicate of https://github.com/ErikEJ/EFCorePowerTools/issues/19

**Closed** 2018-12-20 11:10 UTC
