### ISSUE TITLE
In SQLCE Toolbox v4.7.61.0, the SQL execute duration is incorrect.

### ISSUE THREAD

**Issue by Maximushep** [ErikEJ/SqlCeToolbox#302] opened 2017-03-17 15:23 UTC
We ran a SQL CE 4.0 sql that took about 16-18 seconds in c#.
Running the same on CE Toolbox query window showed about 4 seconds.

Several attempts proved the same, till we used phone timer and discovered CE toolbox taking about 18-20 seconds too.

The Duration listed in status bar is incorrect and not computing correctly.

**Comment by ErikEJ** [comment] 2017-03-17 16:22
Hmmm.. Wonder what I could be doing wrong? What do you think?

https://github.com/ErikEJ/SqlCeToolbox/blob/master/src/GUI/SqlCe35Toolbox/ToolWindows/SqlEditorControl.xaml.cs#L338

**Comment by ErikEJ** [comment] 2017-03-19 13:11
Unable to reproduce, please feel free to re-open if you can provide a reproduction sample (code/database file)

**Comment by ErikEJ** [comment] 2017-03-19 17:56
Thanks for reporting this bug and providing a repro - this is fixed in the latest daily build!

**Closed** 2017-03-19 17:55 UTC

**Comment by Maximushep** [comment] 2017-03-20 02:10
Thanks a lot.

Your tools are awesome and like even your response and turn arounds.
Thanks again.
