### ISSUE TITLE
[SSMS] Scripting Schema and Data to SQLite from SQL Server fails

### ISSUE THREAD

**Issue by Greg90277** [ErikEJ/SqlCeToolbox#1005] opened 2024-11-07 08:57 UTC
The following error happens attempting to script database schema and data to SQLite:

<img width="403" alt="image" src="https://github.com/user-attachments/assets/8c3978bf-54e5-4bdf-9d9d-73da98ec5024">

**Comment by ErikEJ** [comment] 2024-11-07 09:00
Oh. Why not use the VS extension instead??

**Comment by Greg90277** [comment] 2024-11-07 09:04
I was hoping that the SSMS version would allow me to script Views as well...

**Comment by Greg90277** [comment] 2024-11-07 09:14
Oh yeah it would be extremely valuable to be able to script all views also.

**Comment by ErikEJ** [comment] 2024-11-07 09:24
Lack of view support is by design (based on experience): https://github.com/ErikEJ/SqlCeToolbox/issues/858

**Comment by ErikEJ** [comment] 2024-11-07 09:26
Fixing bugs in the SSMS extension is quite low on my priorities, you should be able to use the VS extension

**Comment by ErikEJ** [comment] 2024-11-07 19:43
@Greg90277 Fixed in latest daily build

**Comment by ErikEJ** [comment] 2024-11-07 19:43
If you like my free tools, I would be very grateful for a rating/review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) and/or a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Closed by ErikEJ** 2024-11-07 19:43 UTC
