### ISSUE TITLE
Use column names from table 

### ISSUE THREAD

**Issue by dgxhubbard** [ErikEJ/SqlCeToolbox#632] opened 2018-02-15 17:18 UTC
Just downloaded EF core power tools and it is great. There is an option to 
"Pluralize or singularize object names" and 
"Use table and column names from database".

What I really need is an option to use column names from database, and to singularize object names.
Is that possible?

**Comment by ErikEJ** [comment] 2018-02-15 17:27
No, it is either/or, sorry

**Comment by ErikEJ** [comment] 2018-02-15 17:28
The "column names from database" feature is also kind of broken

**Comment by dgxhubbard** [comment] 2018-02-15 17:30
That's what I thought. Is it possible to do some of this through code generation?

**Comment by ErikEJ** [comment] 2018-02-15 18:05
Please share an example of exactly what you want to acheive

**Comment by ErikEJ** [comment] 2018-02-20 15:53
I am considering making this happen in my Dacpac based model factory

**Comment by dgxhubbard** [comment] 2018-02-20 17:34
I would appreciate it. We have a lot of code that uses our current column names so it would help us.
Thanks

**Comment by ErikEJ** [comment] 2018-02-20 18:09
But do you have a dacpac involved?

**Comment by ErikEJ** [comment] 2018-02-22 08:48
Actually, what is not working with the default behaviour?

**Comment by ErikEJ** [comment] 2018-02-25 07:25
Possible dupe of #640

**Closed by ErikEJ** 2018-02-25 07:25 UTC
