### ISSUE TITLE
Error in Visual Studio 2017 - Unable to load DLL 'e_sqlite3': The specified module could not be found.

### ISSUE THREAD

**Issue by KCarterSr** [ErikEJ/SqlCeToolbox#599] opened 2017-12-19 22:26 UTC
In Visual Studio when I right click on a project, and the select:

EF Core Power Tools --> Reverse Engineer -->
Choose Database Connection --> Select Tables To Script -->
Generate EF Core Model In Project ...

I get the Error below.

I'm using EF Core Power Tools V.1.0.481 Daily build, and I was using the version from VS Gallery.
Both have same Problem.

I checked ...\AppData\Local\Microsoft\VisualStudio\15.0_5f11fda6\Extensions\uba5o5io.zok
and e_sqlite3.dll file (IS LOCATED IN) both x86 and x64 directories.

Thank you

System.TypeInitializationException: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.DllNotFoundException: Unable to load DLL 'e_sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_libversion_number()
   at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
   at SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
   at SQLitePCL.Batteries_V2.Init()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Data.Sqlite.Utilities.BundleInitializer.Initialize()
   at Microsoft.Data.Sqlite.SqliteConnection..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.SqliteDatabaseModelFactory.Create(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ModelScaffolder.Generate(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, String projectPath, String outputPath, String rootNamespace, String contextName, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at ReverseEngineer20.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\projects\sqlcetoolbox\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 111

**Comment by ErikEJ** [comment] 2017-12-20 08:08
What happens if you copy the e_sqlite3.dll file from the x86 folder to the folder above?

**Comment by KCarterSr** [comment] 2017-12-20 15:52
Same thing.

**Comment by ErikEJ** [comment] 2017-12-21 09:54
I am discussing a fix: https://github.com/aspnet/EntityFrameworkCore/issues/10596

**Comment by KCarterSr** [comment] 2017-12-21 15:27
Okay, Thank you.

**Comment by ErikEJ** [comment] 2017-12-22 09:49
Fixed in the latest build, let me know if it works for you!

**Comment by KCarterSr** [comment] 2017-12-22 17:54
Yes it works now, but when I select reverse engineer and point it to my SQLITE database, the only thing that happens is I get a json config file only. There are no code files.

**Comment by ErikEJ** [comment] 2017-12-22 18:00
Check the VS ouput window - does your tabels have primary keys - this is required?

**Comment by KCarterSr** [comment] 2017-12-22 18:43
Sorry, I hadn't noticed the debug windows, that even though it went further than before, I had the error message below.

System.TypeInitializationException: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.DllNotFoundException: Unable to load DLL 'e_sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_libversion_number()
   at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
   at SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
   at SQLitePCL.Batteries_V2.Init()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Data.Sqlite.Utilities.BundleInitializer.Initialize()
   at Microsoft.Data.Sqlite.SqliteConnection..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.SqliteDatabaseModelFactory.Create(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ModelScaffolder.Generate(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, String projectPath, String outputPath, String rootNamespace, String contextName, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at ReverseEngineer20.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\projects\sqlcetoolbox\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 120

**Comment by KCarterSr** [comment] 2017-12-22 18:44
C:\projects\sqlcetoolbox\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 120

**Comment by KCarterSr** [comment] 2017-12-22 18:48
Used daily build from EF Core Power Tools Wiki below.

Useful design-time DbContext features, added to the Visual Studio Solution Explorer context menu.

Watch demo on Channel 9

Download from Visual Studio MarketPlace

Download daily build <------------------------------------

**Comment by ErikEJ** [comment] 2017-12-22 18:51
I cannot reproduce with the latest daily build - can you share a reproduce project and provide VS version

**Comment by KCarterSr** [comment] 2017-12-22 18:52
Do I need to update SQLite/SQL Server Compact Toolbox too?

**Comment by ErikEJ** [comment] 2017-12-22 19:34
No. Which Power Tools version do you have?

**Comment by ErikEJ** [comment] 2017-12-23 07:06
Yes, that was my fix. Let me do some more testing

**Comment by ErikEJ** [comment] 2017-12-24 13:36
I was able to repro. Will try out this fix: https://github.com/aspnet/Microsoft.Data.Sqlite/issues/249#issuecomment-272021431

**Comment by KCarterSr** [comment] 2017-12-25 18:31
Ok, I had saw that too. That might work out.

**Comment by ErikEJ** [comment] 2017-12-26 08:12
Trying this:
```
Install-Package Microsoft.EntityFrameworkCore.Sqlite.Core -Version 2.0.1
Install-Package SQLitePCLRaw.bundle_winsqlite3
```

**Closed** 2017-12-26 10:17 UTC

**Comment by ErikEJ** [comment] 2017-12-26 10:49
Made another attempt at fixing: https://github.com/aspnet/EntityFrameworkCore/issues/10596#issuecomment-353952643 - in the latest daily build - please let me know if i works for you!

**Comment by KCarterSr** [comment] 2017-12-27 13:30
Yes, it worked.
Thank you

**Comment by ErikEJ** [comment] 2017-12-27 13:31
You are welcome, thank you for reporting this issue

**Comment by KCarterSr** [comment] 2017-12-27 14:04
No problem.
