### ISSUE TITLE
When deleting multiple rows after each other, only the first row is actually deleted

### ISSUE THREAD

**Issue by Mertsch** [ErikEJ/SqlCeToolbox#724] opened 2018-08-06 12:46 UTC
When deleting multiple rows after each other, only the first row is actually deleted

### Steps to reproduce
1. Create a new DB
2. Create a new Table with a text column
3. Insert Text into the column and repeat till you have 5 rows
4. Right click the table > Edit top 200 rows
5. Click the Row Header of the first row, press delete to remove it
6. Repeat step 5. until DB is empty
7. Right click the table > Edit top 200 rows
8. Note that only one entry has been deleted

### Further technical details
Toolbox for SSMS 4.7.460
Database engine: SQlite
SSMS version: 17.8.1

**Comment by ErikEJ** [comment] 2018-08-19 15:47
Does you new table have a primary key?

**Comment by Mertsch** [comment] 2018-08-19 15:53
I am not an SQLite expert, so if a new table does not, then no

**Comment by ErikEJ** [comment] 2018-08-19 16:08
In other words: What is the create table script for you new table?

**Comment by Mertsch** [comment] 2018-08-19 16:48
```-- Script Date: 19.08.2018 18:46  - ErikEJ.SqlCeScripting version 3.5.2.75
CREATE TABLE [test] (
  [Id] INTEGER NOT NULL
, [TC] TEXT NOT NULL
, CONSTRAINT [PK_test] PRIMARY KEY ([Id])
);
```

**Comment by ErikEJ** [comment] 2018-12-09 17:38
This is not supported in the edit grid, closing as by design - if you can fix this, a PR for it would be much appreciated.

**Closed by ErikEJ** 2018-12-09 17:38 UTC
