### ISSUE TITLE
Unable to determine the provider name for provider factory of type 'System.Data.SQLite.SQLiteFactory'

### ISSUE THREAD

**Issue by nucasspro** [ErikEJ/SqlCeToolbox#721] opened 2018-06-18 07:02 UTC
I have this error when click finish create ADO.NET Entity Data Model. So, What should i do to fix this?
I use Visual Studio 2017 15.7.3
![image](https://user-images.githubusercontent.com/25147252/41521845-f8734c4c-72fd-11e8-8cd7-7b280c74ad2b.png)

**Comment by ErikEJ** [comment] 2018-06-18 07:04
Duplicate of #710

**Closed by ErikEJ** 2018-06-18 07:04 UTC
