### ISSUE TITLE
Build Table PK default value not rendered

### ISSUE THREAD

**Issue by Tonteria** [ErikEJ/SqlCeToolbox#729] opened 2018-08-14 15:47 UTC
When I use uniqueidentifier as datatype for the Id column and newId() as default value, this is not rendered into the create table script. I can add the default value manually in the script and things are running fine but I would appreciate it to be done automatically. 

### Steps to reproduce

Open BuildTable dialog, insert name, change Datatype to uniqueidentifier, insert newId() in default value column,
Press script button

### Further technical details
Toolbox/Power Tools version: Version 4.7.534.0
Database engine: SQL Compact 4.0.8876.1
Studio 2015 14.0.25431.01 Update 3, 
SSMS 17.8.1

**Comment by ErikEJ** [comment] 2018-08-19 15:57
I am not able to reproduce using SQL Server Compact.

If you are using SQLite, newid() is not a valid default value.

**Comment by ErikEJ** [comment] 2018-08-29 15:21
Closing, feel free to re-open if you provide repro steps

**Closed by ErikEJ** 2018-08-29 15:21 UTC
