### ISSUE TITLE
Bug on bit fields

### ISSUE THREAD

**Issue by mtugnoli** [ErikEJ/SqlCeToolbox#607] opened 2018-01-04 14:05 UTC
Reverse Engineering :

I've found a little bug.
bit fields : the corresponding property in the class is always nullable

es.
  public bool? IsDeleted { get; set; }     <- im my db this field is not nullable

have to be :
  public bool IsDeleted { get; set; }

**Comment by ErikEJ** [comment] 2018-01-04 14:10
Duplicate of #603 - I will investigate upgrading to 2.1 preview

**Closed by ErikEJ** 2018-01-04 14:10 UTC
