### ISSUE TITLE
Theme not updating dynamically

### ISSUE THREAD

**Issue by ManGupt** [ErikEJ/SqlCeToolbox#869] opened 2020-09-21 05:08 UTC
Whenever you change the theme from inside the VS. The plugin remains on older theme till next re-start of VS.

### Steps to reproduce
1. Open VS in a dark theme (ex.).
2. Open plugin for viewing sqlite tables.
3. Change the VS theme to Blue (ex.)
4. Plugin remains in dark theme, till next restart.

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)
Version 4.7.670.0
SQL Server Compact 4.0 Simple DDEX provider - Yes
SQLite ADO.NET Provider included: 1.0.109.0
SQLite Simple DDEX provider - Yes

Database engine: SQlite

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)
VS Community 2019, Version 16.6.0

**Comment by ErikEJ** [comment] 2020-09-21 05:14
Duplicate of #111

**Closed by ErikEJ** 2020-09-21 05:14 UTC

**Comment by ManGupt** [comment] 2020-09-21 05:17
I am sorry, but #111 is not fixed (two year old). Is this not supported even in latest VS 2019?

**Comment by ErikEJ** [comment] 2020-09-21 05:20
Did you not read the issue? The extension still supports VS 2010, so it is not possible due to backwards compat with previous VS versions
