### ISSUE TITLE
Crash when viewing table with no primary key

### ISSUE THREAD

**Issue by ManGupt** [ErikEJ/SqlCeToolbox#870] opened 2020-09-21 05:14 UTC
Whenever we try to view table with no primary key the plugin crashes and takes down the VS with it.

### Steps to reproduce
1. Create table with no primary key
2. Insert some data
3. Try view the data by clicking "Edit top 200".
4. Plugin crashes, once it didn't crash but the VS was unusable had to restart.

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)
Version 4.7.670.0
SQL Server Compact 4.0 Simple DDEX provider - Yes
SQLite ADO.NET Provider included: 1.0.109.0
SQLite Simple DDEX provider - Yes

Database engine: SQlite

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)
VS Community 2019, Version 16.6.0

![4](https://user-images.githubusercontent.com/25338257/93734564-6e0c1180-fbf7-11ea-9230-251c82ece6a9.jpg)
![3](https://user-images.githubusercontent.com/25338257/93734570-706e6b80-fbf7-11ea-9dd4-16f07515b4b5.jpg)

**Comment by ErikEJ** [comment] 2020-09-21 05:19
Please provide exact repro steps, and I will try to prevent the VS crash

**Comment by ManGupt** [comment] 2020-09-21 05:29
Please use following sql commands to create table and insert data: similar to #868

CREATE TABLE types ([id] INTEGER NOT NULL, [code] nvarchar(50) NULL, [desc] nvarchar(250) NULL, [name] nvarchar(30) NOT NULL, [inactive] character DEFAULT ('n') NULL, [end_date] timestamp NULL);

INSERT INTO [types] ([id],[code],[desc],[name],[inactive],[end_date]) VALUES (1, 'c1', 'code 1', 'Dummy', 'n', '');

**Comment by ErikEJ** [comment] 2020-09-21 08:48
The crash here relates to the "timestamp" column, not the lack of a primary key (based on your repro), so duplicate of #868

**Closed by ErikEJ** 2020-09-21 08:48 UTC

**Comment by ManGupt** [comment] 2020-09-23 06:17
Please use the following updated commands:

CREATE TABLE types ([id] INTEGER NOT NULL, [code] nvarchar(50) NULL, [desc] nvarchar(250) NULL, [name] nvarchar(30) NOT NULL, [inactive] character DEFAULT ('n') NULL, [end_date] **nvarchar(50)** NULL);

INSERT INTO [types] ([id],[code],[desc],[name],[inactive],[end_date]) VALUES (1, 'c1', 'code 1', 'Dummy', 'n', '');

**Comment by ErikEJ** [comment] 2020-09-23 06:22
Have you tried this with the latest daily build? (4.7.685)

**Comment by ManGupt** [comment] 2020-09-24 06:19
Thanks I updated to daily build. It is working now.

**Comment by ErikEJ** [comment] 2020-09-24 06:21
Great, and thanks for the feedback - I think this is caused by some async features in newer versions of VS

**Comment by ManGupt** [comment] 2020-09-29 14:33
Hi @ErikEJ ,
I was doing more some more digging and found 1 more issue.
Whenever I close the table opened using above steps.
And tried to open again this rendered sometimes your plugin and sometimes complete VS usable.

SQL:
CREATE TABLE [cat_mapping] (  [id] bigint NULL, [cat] nvarchar(250) NULL);
INSERT INTO [cat_mapping]  ([id] ,[cat]) VALUES ("1","abc^efg");

Error: (now shown more gracefully)

System.InvalidOperationException: Dispatcher processing has been suspended, but messages are still being processed.
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.SafeNativeMethods.MessageBox(HandleRef hWnd, String text, String caption, Int32 type)
   at System.Windows.Forms.MessageBox.ShowCore(IWin32Window owner, String text, String caption, MessageBoxButtons buttons, MessageBoxIcon icon, MessageBoxDefaultButton defaultButton, MessageBoxOptions options, Boolean showHelp)
   at ErikEJ.SqlCeToolbox.WinForms.ResultsetGrid.ResultsetGrid_Load(Object sender, EventArgs e) in C:\projects\sqlcetoolbox\src\GUI\SqlCe35Toolbox\WinForms\ResultsetGrid.cs:line 82
