### ISSUE TITLE
The definition of column <Column Name> must include a data type.

### ISSUE THREAD

**Issue by filippobottega** [ErikEJ/SqlCeToolbox#775] opened 2019-02-19 10:56 UTC
Hello,
  I receive an exception through the "Migrate to SQL Server" command on a SQLite database.
Some tables have columns without a defined data type.

  Best regards,
    Filippo.

### Further technical details
```
---------------------------
Microsoft SQL Server Management Studio
---------------------------
SQLite / SQL Server Compact Toolbox
System.Exception: Message   : La definizione della colonna 'p' deve includere un tipo di dati.
Level     : 15
State     : 13
Procedure : 
Line      : 2
Source    : .Net SqlClient Data Provider
Number    : 173
Server    : 

CREATE TABLE [fts4_libraries] (
  [p]  NULL
, [s]  NULL
);
   in ErikEJ.SqlCeScripting.ServerDBRepository.RunCommand(String sql)
   in ErikEJ.SqlCeScripting.ServerDBRepository.RunCommands(String scriptPath)
   in ErikEJ.SqlCeScripting.ServerDBRepository.ExecuteSqlFile(String scriptPath)
   in ErikEJ.SqlCeToolbox.Commands.DatabaseMenuCommandsHandler.bw_DoExportWork(Object sender, DoWorkEventArgs e) in C:\projects\sqlcetoolbox\src\GUI\SqlCe35Toolbox\Commands\DatabaseMenuCommandsHandler.cs:riga 458
   in System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   in System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

Database engine: SQlite

Visual Studio or SSMS version: SSMS 17.9.1

**Comment by ErikEJ** [comment] 2019-02-19 13:06
You must update your schema to have column types defined, as SQL Server requires a defined column type. Semi duplicate of https://github.com/ErikEJ/SqlCeToolbox/issues/350

**Comment by ErikEJ** [comment] 2019-02-19 13:07
Or exclude the involved table from the migration

**Closed by ErikEJ** 2019-02-19 13:06 UTC

**Comment by filippobottega** [comment] 2019-02-19 14:15
Hello Erik,
  what do you think about setting "text" type by default when a column doesn't have a data type specified?

  Filippo

**Comment by ErikEJ** [comment] 2019-02-19 14:18
Are you talking about the SQL Server data type "text" - then I do not think that is a good idea. But maybe nvarchar(max) ?

**Comment by filippobottega** [comment] 2019-02-19 14:22
Yes, nvarchar(max) or nvarchar(4000) is better. But another idea could be to let the user setting the data type in a new option on Advanced section under SQLCE/SQLite Toolbox settings.

**Comment by ErikEJ** [comment] 2019-02-19 14:27
PRs accepted 😎
