### ISSUE TITLE
Can't add mysql server.

### ISSUE THREAD

**Issue by LordXaosa** [ErikEJ/SqlCeToolbox#685] opened 2018-04-05 16:29 UTC
Net Core project.
Trying to add MySQL Db, list is empty
![image](https://user-images.githubusercontent.com/1145380/38378709-31ca20f0-3907-11e8-8ddc-aa39b4734af9.png)
after trying to add list is still empty
![image](https://user-images.githubusercontent.com/1145380/38378742-4f693830-3907-11e8-8bc9-dca67976e698.png)
Testing connection is ok, it says connection successful, and db list obtained well.
What I'm doing wrong?
Also I tried adding it in server list, it was added here, but list is still empty.
![image](https://user-images.githubusercontent.com/1145380/38378927-d73b505e-3907-11e8-9341-f1365e4f0571.png)

**Comment by ErikEJ** [comment] 2018-04-05 16:48
MySQL is not (yet) supported - duplicate of #617 - PRs accepted!

**Closed by ErikEJ** 2018-04-05 16:48 UTC
