### ISSUE TITLE
problem using  SQL Server Compact 4.0 (Simple by ErikEJ)

### ISSUE THREAD

**Issue by aymen0406** [ErikEJ/SqlCeToolbox#278] opened 2017-02-27 21:17 UTC
i'm always getting an error saying "an error occurred while retrieving the information from the database: The specified type is not supported by this selector" while trying to create a dataset for a report viewer 
i'm using your plug in "SQL Server Compact 4.0 (Simple by ErikEJ) 
![problem](https://cloud.githubusercontent.com/assets/26072493/23380307/8e089d1a-fd3a-11e6-84b4-99ef860b47c3.PNG)

**Comment by ErikEJ** [comment] 2017-02-27 21:23
- The provider is called "Simple" for a reason! No support for Data Source Configuration Wizard -
Is this a standard MS Report Viewer report, you are creating?

**Comment by aymen0406** [comment] 2017-02-27 21:26
yes i'm trying to create Ms Report viewer  report

**Comment by ErikEJ** [comment] 2017-02-27 21:28
See the related issue here: https://github.com/ErikEJ/SqlCeToolbox/issues/39

**Comment by ErikEJ** [comment] 2017-02-27 21:32
Blog post with details for doing this in code: https://blogs.msdn.microsoft.com/sqlforum/2011/04/27/walkthrough-assign-dataset-dynamically-created-in-code-to-your-local-report-with-reportviewer/ (Replace SqlConnection with SqlCeConnection etc)

**Comment by ErikEJ** [comment] 2017-02-27 21:38
Closing as duplicate of #39

**Closed by ErikEJ** 2017-02-27 21:38 UTC

**Comment by raminmjj** [comment] 2020-09-08 04:38
I have the same problem for SQLite in create DataSet.
I used the [workflow](https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider) to Install requirements and install the daily version of SQLite Toolbox.

**Comment by ErikEJ** [comment] 2020-09-08 05:51
@raminmjj This is by design

**Comment by raminmjj** [comment] 2020-09-08 15:45
thank you.
I tried on another device but it was not successful.
is there any solution?

**Comment by ErikEJ** [comment] 2020-09-08 15:51
What was not working?
And what are you trying to do?

**Comment by raminmjj** [comment] 2020-09-08 16:03
I try to regenerate or edit DataSet in Visual Studio.
![image](https://user-images.githubusercontent.com/991847/92500404-56558600-f212-11ea-99dc-697b02cb7c5e.png)

database file:
[Database_Dataset_Error.zip](https://github.com/ErikEJ/SqlCeToolbox/files/5189467/Database_Dataset_Error.zip)

**Comment by ErikEJ** [comment] 2020-09-08 16:12
See my 4 year old comment - this is not supported.

**Comment by raminmjj** [comment] 2020-09-08 16:17
Ok.
Thank you.
