### ISSUE TITLE
What about SQLite standalone .exe + GUI?

### ISSUE THREAD

**Issue by win32nipuh** [ErikEJ/SqlCeToolbox#862] opened 2020-06-29 13:38 UTC
I have downloaded the standalone version but it works with SQL Compact only. 
Is it possible to build the exe+GUI  for SQLite? 
Thnx

**Comment by ErikEJ** [comment] 2020-06-29 14:09
Duplicate of #850 - please add your upvote

**Closed by ErikEJ** 2020-06-29 14:09 UTC
