### ISSUE TITLE
Add support for Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by PawelFojt** [ErikEJ/SqlCeToolbox#980] opened 2024-03-08 10:37 UTC
I encountered an issue while attempting to connect to SQL Server using the TrustServerCertificate=true parameter in the connection string. It appears that the connection string generated by the toolbox contains spaces, and unfortunately, there is no way to remove these spaces.

This issue prevents successful connection to the SQL Server due to the presence of spaces in the connection string. As a result, the TrustServerCertificate=true parameter cannot be used effectively.

It would be beneficial to address this issue by either providing a method to eliminate spaces from the generated connection string or by ensuring that connection strings generated by the toolbox do not contain spaces, especially when using parameters such as TrustServerCertificate.

Thank you for your attention to this matter.

### Steps to reproduce:
Right click on Data Connections -> Add SQL Server Connection..
![image](https://github.com/ErikEJ/SqlCeToolbox/assets/33200685/936e1883-f883-477a-9fe4-68becaea0782)

Test connection is okey.
![image](https://github.com/ErikEJ/SqlCeToolbox/assets/33200685/50c69118-cfce-4271-bdb2-bf6916f6264c)

And here Trust Server Certificate has spaces. 
![image](https://github.com/ErikEJ/SqlCeToolbox/assets/33200685/5b08f799-38f3-42f3-9509-92c3f306a9f5)

If I click OK in the Connection Properties Window, the following error occurs.
![image](https://github.com/ErikEJ/SqlCeToolbox/assets/33200685/a8b05bb7-8969-48f7-8f6d-eb5921c0d9fc)

### Further technical details:
Toolbox/Power Tools version: 4.8.776

Database engine: SQL Server

Visual Studio or SSMS version: Visual Studio 2022 17.8.6, SSMS 19.3

**Comment by ErikEJ** [comment] 2024-03-08 11:19
It is caused by differences in connection strings between System.Data.SqlClient  and Microsoft.Data.SqlClient

**Comment by ErikEJ** [comment] 2024-03-18 13:06
@PawelFojt Ping?

**Comment by ErikEJ** [comment] 2024-03-18 16:06
I added a fix for this in the latest daily build from VSIX gallery, could you try it and let me know?

**Comment by ErikEJ** [comment] 2024-03-18 16:06
See https://github.com/ErikEJ/SqlCeToolbox/commit/bc7eb886a707f97c0f815e123c757ec88d8735ae

**Comment by PawelFojt** [comment] 2024-03-18 21:48
Now, when connected to the database, there's no issue, and I can even see that database under "Data Connections." However, when I try to right click on my DB -> script database -> Script schema.., the same error pops up. Additionally, I don't see a single table under the icon of my database.
![image](https://github.com/ErikEJ/SqlCeToolbox/assets/33200685/73479738-6faf-43db-990c-b18cb205259f)
So I think this issue occurs in multiple places within the application.

**Comment by ErikEJ** [comment] 2024-03-18 21:54
Where are you right clicking?

**Comment by PawelFojt** [comment] 2024-03-18 22:02
On the icon of the database I connected to.

**Comment by ErikEJ** [comment] 2024-03-19 07:17
@PawelFojt OK, you are basically asking for support for Microsoft.Data.SqlClient - it was never added. I will look into it, 

In the meantime you can create a connection using the legacy Provider:

![image](https://github.com/ErikEJ/SqlCeToolbox/assets/4169187/198e4eb7-57d4-41ad-b5ea-bb37791f7d10)

**Comment by ErikEJ** [comment] 2024-03-19 09:06
@PawelFojt  I added a fix for this in the latest daily build from VSIX gallery, could you try it and let me know?

**Closed** 2024-03-19 09:06 UTC
Labels: enhancement, gui

**Comment by PawelFojt** [comment] 2024-03-20 07:53
The database connection is working, and there are no errors popping up when using the 'Script schema..' command. However, I don't see any tables. When I connect to the same database using SSMS, I can see several tables.
![image](https://github.com/ErikEJ/SqlCeToolbox/assets/33200685/7976800f-2055-4748-9c9e-68437f8329ca)

**Comment by ErikEJ** [comment] 2024-03-20 08:10
I am not able to repro, can you share a sample schema?

**Comment by PawelFojt** [comment] 2024-03-20 08:27
Right click on Data Connections -> Add SQL Server Connection.. -> fill Server name -> change Authentication to SQL Server Authentication -> fill User name and Password -> check Trust Server Certificate -> Test Connection is OK -> Click OK -> now I see myDb below Data Connections (but I don't see any table) - right click on myDb -> Script Database.. -> Script Schema -> here I also don't see any table

**Comment by ErikEJ** [comment] 2024-03-20 09:11
> Data Connections (but I don't see any table)

Correct, the tool does not list any server tables - this is by design

I am unable to repro - I see tables listed.
